### PR TITLE
Grj module dev

### PR DESCRIPTION
**Pull request by johnson452**
Final completion of the Albedo module, associated testing, and diagnostics. 

Some notes: 
a. The solutions to the total radiation equations (I_up and I_down) have an assumed Icm I0 (the initial flux in each direction) is equal to 1. (At night the incoming flux is set to zero, but the outgoing flux is allowed to float). Sunset causes some issues, this wouldn't be a problem with an atmosphere model which would have very low incident flux at these times, but for now I have a cutoff which makes the plots look much more manageable. (Doesn't effect the model) 

b. Single model canopy layer, (we don't consider the canopy breakdown as a function of height, but a single semi-transparent layer determined by the plant functional types.

c. Diagnostics has been expanded based to include all the new state variables on the way it was re-written in the last PR.

d. General bugfixes for the albedo module equations. 

e. The albedo outputs should be ready (based on the state.I_XX) to be utilized by modules for the radiative fluxes.

Some thoughts: 
1. It would be nice to have the default parameters be saved like App, State, Grid (as Parameters_default) or something so we can not break the tests when we change the parameters.

### CODE REVIEW

**Comment by ConghaoYi** [comment]
Looks good.

**Review by ConghaoYi — COMMENTED** [review]
Great. Some of the state data would be helpful to my module as well.

**Comment by hstone31** [comment]
Looks good - Happy with changes to the diagnostics file

**Review by hstone31 — COMMENTED** [review]
Looks good

**Comment by hstone31** [comment]
How do you determine if it's night? If mu <= 0?

Warning - I think this might not work if we change our deltaT

**Comment by johnson452** [comment]
Yes, night is determined by \mu <= 0. I believe it's fine since \mu is calculated entirely based on the day (as a decimal number for parts of the day). The calculations will be okay for each of the modules since they always know the correct time at step, i, pulling the time (in fractional days) from grid.time(i). But there is an integration test in test_albedo_module which will break if we change the time or stepsize of the time from the default.

**Pull request merged**
