### PR TITLE
Stone dev

### PR DESCRIPTION
**Pull request by hstone31**
See previous Pull Request.

Added Model_Radiation_Fluxes module
Added input csv file and way to add in daily data
Added new diagnostics figures
Added new table
Added new connections between modules

NOTE:
- There is still a bug with the total solar radiation absorbed by vegetation, but I have isolated it. Tests/Pre-Commit all work.

### CODE REVIEW

**Review by johnson452 — APPROVED** [review]
Deleted some unnecessary files, then merged.

**Comment by hstone31** [comment]
How do you determine if it's night? If mu <= 0?

Warning - I think this might not work if we change our deltaT

**Comment by johnson452** [comment]
Yes, night is determined by \mu <= 0. I believe it's fine since \mu is calculated entirely based on the day (as a decimal number for parts of the day). The calculations will be okay for each of the modules since they always know the correct time at step, i, pulling the time (in fractional days) from grid.time(i). But there is an integration test in test_albedo_module which will break if we change the time or stepsize of the time from the default.

**Comment by johnson452** [comment]
The output plots from the diagnostics looks good from the radiative fluxes module. 

Could you explain what precisely is in the csv file? (Variables / any formatting, thanks!)

Did the bug get ironed out of "total radiation absorbed" in future commits? If so could you link which commit or explain where you isolated it to be?

**Comment by hstone31** [comment]
Good questions -

The csv contains daily fluxes for radiation (in W/m2). It's processed in the radiation model and then saved to the State class as State.radiation.vis_in, State.radiation.vis_out, State.radiation.IR_in, and State.radiation.IR_out. I grabbed them from a MET station my lab uses.

**Comment by hstone31** [comment]
For the second question. I debugged my code, and some of the albedo outputs for fractional values were coming out beyond the range of expected values. Resetting their ranges to -1 and 1 seemed to solve the issue. See PR10.

**Pull request merged**
